#This needs updating

before_install:
  - sudo apt-get update
rvm:
- 2.1.5
- 2.1.4
- 2.1.1
- 2.0.0

services:
  - mongodb

addons:
  code_climate:
    repo_token: dbff2f8dc258f57e456b6c1980bef3159ae268fe03291656251e140e91d0e6d6
